version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7
        environment: 
            PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: |
              sudo pip install pipenv
              pipenv install
              pipenv shell
              pipenv python tests.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

